<?php

$brand_logo = [
	["src" => "transpaint.png"		],
	["src" => "lazor.png"			],
	["src" => "versatile.png"		],
	["src" => "ymc.png"				],
	["src" => "stanley2.png"		],
	["src" => "irwin2.png"			],
	["src" => "lenox.png"			],
	["src" => "LAVOR_NEW.png"		],
	["src" => "asteel.png"			],
	["src" => "cms.png"				],
	["src" => "dulux.png"			],
	["src" => "bosch.png"			],
	["src" => "hikoki.png"			],
	["src" => "makita2.png"			],
	["src" => "sika2.png"			],
	["src" => "yale2.png"			],
	["src" => "philips.png"			],
	["src" => "karcher.png"			],
	["src" => "abus.png"			],
	["src" => "tri_circle2.png"		],
	["src" => "3m.png"				],
	["src" => "hardex.png"			],
	["src" => "energizer.png"		],
	["src" => "eveready.png"		],
	["src" => "koya2.png"			],
	["src" => "prima.png"			],
	["src" => "everlast.png"		],
	["src" => "ecogreen.png"		],
	["src" => "kingkong.png"		],
	["src" => "selleys.png"			],
	["src" => "rexco.png"			],
	["src" => "vip.png"				],
	["src" => "enviomatt2.png"		],
	["src" => "envioclean2.png"		],
	["src" => "domina2.png"			],
	["src" => "galuzinc2.png"		],
	["src" => "AKAIDO.png"			],
	["src" => "INA.png"				],
	["src" => "KHE_NEW.png"			],
	["src" => "tekiro.png"			],
	["src" => "WD40.png"			],
];

